---
- hosts: 127.0.0.1
  vars:
    citadel_bucket: 'balanced-citadel'
    secrets:
      - key: HUBOT_HIPCHAT_TOKEN
        value: "{{ lookup('citadel', '/hubot/HUBOT_HIPCHAT_TOKEN') }}"

      - key: HUBOT_HIPCHAT_JID
        value: "{{ lookup('citadel', '/hubot/HUBOT_HIPCHAT_JID') }}"

      - key: HUBOT_HIPCHAT_PASSWORD
        value: "{{ lookup('citadel', '/hubot/HUBOT_HIPCHAT_PASSWORD') }}"

  tasks:
    - name: write secrets out
      template: >
        src=secrets.env.j2
        dest={{ secrets_dir }}/secrets.env
        mode=0400
