---
- hosts: 127.0.0.1
  vars:
    citadel_bucket: 'balanced-citadel'
    secrets:
      - key: HUBOT_HIPCHAT_TOKEN
        value: "{{ lookup('citadel', 'hubot/HUBOT_HIPCHAT_TOKEN').strip() }}"

      - key: HUBOT_HIPCHAT_JID
        value: "{{ lookup('citadel', 'hubot/HUBOT_HIPCHAT_JID').strip() }}"

      - key: HUBOT_HIPCHAT_PASSWORD
        value: "{{ lookup('citadel', 'hubot/HUBOT_HIPCHAT_PASSWORD').strip() }}"

      - key: HUBOT_PAGERDUTY_API_KEY
        value: "{{ lookup('citadel', 'hubot/HUBOT_PAGERDUTY_API_KEY').strip() }}"

      - key: HUBOT_PAGERDUTY_SERVICE_API_KEY
        value: "{{ lookup('citadel', 'hubot/HUBOT_PAGERDUTY_SERVICE_API_KEY').strip() }}"

      - key: HUBOT_TRELLO_KEY
        value: "{{ lookup('citadel', 'hubot/HUBOT_TRELLO_KEY').strip() }}"

      - key: HUBOT_TWITTER_CONSUMER_KEY
        value: "{{ lookup('citadel', 'hubot/HUBOT_TWITTER_CONSUMER_KEY').strip() }}"

      - key: HUBOT_TWITTER_CONSUMER_SECRET
        value: "{{ lookup('citadel', 'hubot/HUBOT_TWITTER_CONSUMER_SECRET').strip() }}"

      - key: HUBOT_TWITTER_ACCESS_TOKEN
        value: "{{ lookup('citadel', 'hubot/HUBOT_TWITTER_ACCESS_TOKEN').strip() }}"

      - key: HUBOT_TWITTER_ACCESS_TOKEN_SECRET
        value: "{{ lookup('citadel', 'hubot/HUBOT_TWITTER_ACCESS_TOKEN_SECRET').strip() }}"

  tasks:
    - name: write secrets out
      template: >
        src=templates/secrets.env.j2
        dest={{ secrets_dir | default('.') }}/secrets.env
        mode=0644
